### ISSUE TITLE
Improve schedule command message

### ISSUE THREAD

**Issue by Nihirraa** [AY2425S1-CS2103T-T11-4/tp#113]
<img width="363" alt="Screenshot 2024-10-31 at 2 18 30 PM" src="https://github.com/user-attachments/assets/06ecfa57-3e97-44f4-b785-ad8789e15b17">

Might be better if this command prompted "Wrong date format" instead of no matching persons

**Comment by aditig0305** [comment]
Fixed
<img width="685" alt="image" src="https://github.com/user-attachments/assets/e2036bd0-a356-402d-8a4c-a2e37400ffd4">
