### ISSUE TITLE
[PE-D][Tester B] Java version for mac

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T11-4/tp#198]
I installed java as stated by the DG on a mac and an error is thrown when trying to run the app. It might be better to specify the version which you want installed i.e. zulu which includes javafx.

-------------
Labels: `type.DocumentationBug` `severity.High`
original: GabrielCWT/ped#4

**Comment by nayanaamahesh** [comment]
OpenJDK Runtime Environment Zulu17.50+19-CA (build 17.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu17.50+19-CA (build 17.0.11+9-LTS, mixed mode, sharing)
