### ISSUE TITLE
[PE-D][Tester A] Edit description wrong

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-4/tp#218]
Edit does not remove tags + cannot submit a patient without a tag.

Bug found in user guide, edit command instruction.

![image.png](https://raw.githubusercontent.com/CreditableX/ped/main/files/b2795dc9-a521-4097-9827-0ac486a65854.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: CreditableX/ped#7

**Comment by nayanaamahesh** [comment]
ug update
