### ISSUE TITLE
[PE-D][Tester D] filter t/HIGH RISK with high risk all caps works, although intended parameter allowed is High Risk, tags are not said to be case insensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-4/tp#232]
![image.png](https://raw.githubusercontent.com/Reallyeasy1/ped/main/files/99eda743-5485-43bf-89e0-2ed1c1ad6f5c.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Reallyeasy1/ped#4

**Comment by nayanaamahesh** [comment]
update ug
