### ISSUE TITLE
[PE-D][Tester B] Delete Command and Date Command UML Diagram

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T11-4/tp#239]
1. Under "Delete Feature"
`DeleteCommandParser` has a private modifier for attributes but it leads to nothing.

2. Under "[Proposed] Adding an End Time to the Date Feature with Duplicate/Overlap Prevention"
`DateCommandParser` has a private modifier for attributes but it leads to nothing.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: GabrielCWT/ped#12

**Comment by nayanaamahesh** [comment]
<img width="838" alt="image" src="https://github.com/user-attachments/assets/2e99f29a-2bbf-4dd0-816b-010add5b2578">
